name = "football-public-api"
main = "src/index.js"
compatibility_date = "2026-10-05"

[vars]
SUPABASE_URL = "https://woggzixprvyjnfjzsglz.supabase.co"
GITHUB_MIRROR_URL = "https://raw.githubusercontent.com/nyeinchanaung75299-eng/football-stream-app/feed/public/matches.json"

[[routes]]
pattern = "football-api.nyeinchanaung.us.ci"
custom_domain = true

