name: football_admin
description: Football streaming admin app starter.
publish_to: "none"
version: 2.5.1+17

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  intl: ^0.20.0
  shared_preferences: ^2.5.3
  http: ^1.2.2
  posthog_flutter: ^5.40.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
