#!/usr/bin/env python3
"""Keep the native iOS WKWebView player identical to the Safari player."""
import argparse
from pathlib import Path
import re


def generate(source: str) -> str:
    style = re.search(r"<style>.*?</style>", source, re.S)
    body = re.search(
        r'<body>\s*(.*?)\s*<script src="flutter_bootstrap.js" async></script>',
        source,
        re.S,
    )
    if style is None or body is None:
        raise ValueError("Expected shared player style/body/bootstrap markers.")
    return (
        '<!DOCTYPE html>\n<!-- Generated by scripts/generate_embedded_player.py. -->\n'
        '<html><head><meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        '<meta name="referrer" content="no-referrer">\n'
        '<title>NCA Player</title>\n'
        + style.group(0)
        + '\n</head>\n<body>\n'
        + body.group(1)
        + '\n</body>\n</html>\n'
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    generated = generate((root / "user_app/web/index.html").read_text(encoding="utf-8"))
    destination = root / "user_app/assets/embedded_player.html"
    if args.check:
        if not destination.exists() or destination.read_text(encoding="utf-8") != generated:
            raise SystemExit("Embedded player is stale; run scripts/generate_embedded_player.py.")
        print("Shared Safari/WKWebView player asset is current.")
    else:
        destination.write_text(generated, encoding="utf-8", newline="\n")
        print("Generated shared Safari/WKWebView player asset.")


if __name__ == "__main__":
    main()
